(function(){
  'use strict';
  const VERSION='6.2.1';
  const BUILD='2026-08-14-v6.2.1-refinement-parental-integration';
  const VISITED_KEY='temple_visited_v1';
  const COLLECTED_KEY='temple_collected_v2';
  const LAST_KEY='temple_last_chamber_v2';
  const SESSION_KEY='temple_refinement_entered_v1';
  const WALLPAPER_ZIP='./downloads/temple-of-maat-parental-powers-wallpapers-v5.2.3.zip';
  let currentId='';
  let powers=[];
  let nameIndex=[];

  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pad=n=>String(n||'').padStart(2,'0');
  function storage(){try{return window.__templeLocal||localStorage;}catch(_){return {getItem:()=>null,setItem:()=>{}};}}
  function session(){try{return window.__templeSession||sessionStorage;}catch(_){return {getItem:()=>null,setItem:()=>{}};}}
  function readSet(key){try{const a=JSON.parse(storage().getItem(key)||'[]');return new Set(Array.isArray(a)?a.map(pad):[]);}catch(_){return new Set();}}
  function saveSet(key,set){try{storage().setItem(key,JSON.stringify([...set].sort()));}catch(_){}}
  function chamber(id){id=pad(id);return powers.find(p=>pad(p.id)===id)||null;}
  function setCurrent(id,{visited=true}={}){id=pad(id);if(!chamber(id))return;currentId=id;try{storage().setItem(LAST_KEY,id);}catch(_){}if(visited)markVisited(id);refreshDock();refreshProgress();}
  function markVisited(id){const s=readSet(VISITED_KEY);id=pad(id);if(!s.has(id)){s.add(id);saveSet(VISITED_KEY,s);document.dispatchEvent(new CustomEvent('temple:visited-change',{detail:{id}}));}}
  function collect(id){id=pad(id);if(!chamber(id))return;const s=readSet(COLLECTED_KEY);if(!s.has(id)){s.add(id);saveSet(COLLECTED_KEY,s);document.dispatchEvent(new CustomEvent('temple:collection-change',{detail:{id,collected:true}}));}refreshDock();refreshProgress();renderSealLibraryCounts();}
  function hash32(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
  function fireMotif(id,cx,cy,s,color){id=Number(id)||1;const sw=Math.max(1.4,s*.018);if(id===1){let d='';for(let i=0;i<38;i++){const t=i/37*Math.PI*2.1,r=s*(.05+.34*i/37);const x=cx+r*Math.cos(t),y=cy+r*Math.sin(t);d+=(i?' L ':'M ')+x.toFixed(1)+' '+y.toFixed(1);}return `<path d="${d}" fill="none" stroke="${color}" stroke-width="${sw}" stroke-linecap="round"/>`;}
    if(id===2)return `<path d="M ${cx-s*.34} ${cy} A ${s*.28} ${s*.28} 0 0 1 ${cx} ${cy} A ${s*.28} ${s*.28} 0 0 1 ${cx+s*.34} ${cy}" fill="none" stroke="${color}" stroke-width="${sw}"/><circle cx="${cx}" cy="${cy}" r="${s*.045}" fill="${color}"/>`;
    if(id===3)return `<path d="M ${cx-s*.34} ${cy-s*.23} L ${cx-s*.06} ${cy+s*.24} M ${cx+s*.34} ${cy-s*.23} L ${cx+s*.06} ${cy+s*.24} M ${cx-s*.34} ${cy-s*.23} L ${cx-s*.06} ${cy-s*.23} M ${cx+s*.06} ${cy-s*.23} L ${cx+s*.34} ${cy-s*.23}" fill="none" stroke="${color}" stroke-width="${sw}" stroke-linecap="round"/>`;
    if(id===4)return `<path d="M ${cx} ${cy+s*.34} C ${cx-s*.34} ${cy+s*.08},${cx-s*.25} ${cy-s*.35},${cx} ${cy-s*.38} C ${cx+s*.25} ${cy-s*.35},${cx+s*.34} ${cy+s*.08},${cx} ${cy+s*.34} Z M ${cx-s*.18} ${cy+s*.20} L ${cx+s*.18} ${cy-s*.20}" fill="none" stroke="${color}" stroke-width="${sw}" stroke-linecap="round"/>`;
    if(id===5)return `<rect x="${cx-s*.29}" y="${cy-s*.29}" width="${s*.58}" height="${s*.58}" fill="none" stroke="${color}" stroke-width="${sw}"/><path d="M ${cx-s*.29} ${cy} H ${cx+s*.29} M ${cx} ${cy-s*.29} V ${cy+s*.29}" stroke="${color}" stroke-width="${sw}"/>`;
    if(id===6)return `<path d="M ${cx-s*.30} ${cy-s*.23} L ${cx} ${cy-s*.04} L ${cx+s*.30} ${cy-s*.23} M ${cx-s*.30} ${cy} L ${cx} ${cy+s*.19} L ${cx+s*.30} ${cy} M ${cx-s*.30} ${cy+s*.23} L ${cx} ${cy+s*.42} L ${cx+s*.30} ${cy+s*.23}" fill="none" stroke="${color}" stroke-width="${sw}" stroke-linecap="round"/>`;
    return `<path d="M ${cx+s*.25} ${cy-s*.24} A ${s*.36} ${s*.36} 0 1 1 ${cx-s*.30} ${cy-s*.13}" fill="none" stroke="${color}" stroke-width="${sw}" stroke-linecap="round"/><path d="M ${cx-s*.30} ${cy-s*.13} L ${cx-s*.16} ${cy-s*.20} L ${cx-s*.20} ${cy-s*.05} Z" fill="${color}"/>`;
  }
  function chamberMark(p,cx,cy,s,color){const seed=hash32(`${p.id}|${p.law}|${p.office}|${p.thirdName}`);const count=5+(seed%4);const pts=[];for(let i=0;i<count;i++){const n=(seed>>>((i%4)*8))&255;const a=-Math.PI/2+i*Math.PI*2/count+((n-128)/128)*.14;const r=s*(.42+.42*((n^((seed>>>16)&255))/255));pts.push([cx+r*Math.cos(a),cy+r*Math.sin(a)]);}return `<polygon points="${pts.map(q=>q.map(v=>v.toFixed(1)).join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="${Math.max(1.3,s*.02)}" stroke-linejoin="round"/>`;}
  function sealSvg(p,size=420){const S=size,c=S/2,outer=S*.405,fire=p.fire?.color||'#d4af37',pillar=p.pillar==='Jachin'?'#2563eb':p.pillar==='Boaz'?'#10b981':'#40e0d0',ink='#261a12',warm='#8c3a2b',sw=Math.max(2,S*.006);let ticks='';for(let i=0;i<12;i++){const a=-Math.PI/2+i*Math.PI*2/12,r1=outer*.95,r2=outer*(i%3===0?1.04:.995);ticks+=`<line x1="${(c+r1*Math.cos(a)).toFixed(1)}" y1="${(c+r1*Math.sin(a)).toFixed(1)}" x2="${(c+r2*Math.cos(a)).toFixed(1)}" y2="${(c+r2*Math.sin(a)).toFixed(1)}" stroke="${i%2?pillar:fire}" stroke-width="${S*.003}"/>`;}
    let pillars='';if(p.pillar==='Middle'){for(const x of [c-S*.18,c+S*.18])pillars+=`<path d="M ${x} ${c-S*.04} V ${c+S*.18} M ${x-S*.022} ${c-S*.04} H ${x+S*.022} M ${x-S*.022} ${c+S*.18} H ${x+S*.022}" stroke="${pillar}" stroke-width="${sw}"/>`;}else{const x=p.pillar==='Jachin'?c-S*.19:c+S*.19;pillars=`<path d="M ${x} ${c-S*.05} V ${c+S*.19} M ${x-S*.026} ${c-S*.05} H ${x+S*.026} M ${x-S*.026} ${c+S*.19} H ${x+S*.026}" stroke="${pillar}" stroke-width="${sw}"/>`;}
    const human=`<g fill="none" stroke="${pillar}" stroke-width="${S*.003}"><ellipse cx="${c}" cy="${c+S*.02}" rx="${S*.105}" ry="${S*.155}"/><ellipse cx="${c-S*.075}" cy="${c+S*.065}" rx="${S*.09}" ry="${S*.12}"/><ellipse cx="${c+S*.075}" cy="${c+S*.065}" rx="${S*.09}" ry="${S*.12}"/></g><g fill="none" stroke="${ink}" stroke-width="${sw}" stroke-linecap="round"><circle cx="${c}" cy="${c-S*.055}" r="${S*.025}"/><path d="M ${c} ${c-S*.03} V ${c+S*.075} M ${c} ${c} L ${c-S*.105} ${c+S*.035} M ${c} ${c} L ${c+S*.105} ${c+S*.035} M ${c-S*.105} ${c+S*.035} L ${c-S*.06} ${c-S*.04} M ${c+S*.105} ${c+S*.035} L ${c+S*.06} ${c-S*.04} M ${c} ${c+S*.075} L ${c-S*.07} ${c+S*.19} M ${c} ${c+S*.075} L ${c+S*.07} ${c+S*.19}"/></g><circle cx="${c}" cy="${c+S*.012}" r="${S*.012}" fill="${fire}"/>`;
    const feather=`<g fill="none" stroke="${warm}" stroke-width="${S*.003}" stroke-linecap="round"><path d="M ${c} ${c+outer*.43} V ${c+outer*.72}"/>${[0,1,2,3,4].map(i=>{const y=c+outer*(.47+i*.05);return `<path d="M ${c} ${y} L ${c-S*(.045+i*.002)} ${y-S*.013} M ${c} ${y} L ${c+S*(.030+i*.002)} ${y-S*.010}"/>`;}).join('')}</g>`;
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${S} ${S}" width="${S}" height="${S}" role="img" aria-label="Human-origin seal of ${esc(p.thirdName)}"><circle cx="${c}" cy="${c}" r="${outer}" fill="none" stroke="${ink}" stroke-width="${sw}"/><circle cx="${c}" cy="${c}" r="${outer*.91}" fill="none" stroke="${warm}" stroke-width="${S*.003}"/><circle cx="${c}" cy="${c}" r="${S*.335}" fill="none" stroke="${pillar}" stroke-width="${S*.003}"/>${ticks}<text x="${c}" y="${c-outer*.75}" text-anchor="middle" font-family="Georgia,serif" font-size="${S*.065}" font-weight="700" fill="${ink}">${esc(p.id)}</text><g>${fireMotif(p.fire?.id,c,c-outer*.52,S*.19,fire)}</g>${pillars}${human}${chamberMark(p,c,c+S*.045,S*.07,warm)}${feather}<text x="${c}" y="${c+outer*.80}" text-anchor="middle" font-family="ui-monospace,monospace" font-size="${S*.032}" font-weight="700" fill="${ink}">${esc(String(p.thirdName||'').toUpperCase())}</text><text x="${c}" y="${c+outer*.90}" text-anchor="middle" font-family="ui-monospace,monospace" font-size="${S*.018}" font-weight="700" fill="${pillar}">${esc(String(p.pillar||'').toUpperCase())} • ${esc(String(p.fire?.name||'').toUpperCase())}</text></svg>`;
  }
  function svgDataUri(svg){return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);}
  async function downloadSealPng(p,button){const old=button?.textContent;if(button){button.disabled=true;button.textContent='Rendering…';}try{const svg=sealSvg(p,2048),blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url;});const canvas=document.createElement('canvas');canvas.width=2048;canvas.height=2048;const ctx=canvas.getContext('2d',{alpha:true});ctx.clearRect(0,0,2048,2048);ctx.drawImage(img,0,0,2048,2048);URL.revokeObjectURL(url);const png=await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('PNG export failed')),'image/png',1));saveBlob(png,`temple-seal-${p.id}-${String(p.thirdName).toLowerCase().replace(/[^a-z0-9]+/g,'-')}.png`);}catch(e){console.error(e);alert('Seal export failed: '+(e?.message||e));}finally{if(button){button.disabled=false;button.textContent=old;}}}
  function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  function inferFromText(text){text=String(text||'').replace(/\s+/g,' ').trim();let m=text.match(/\bCHAMBER\s*0?(\d{1,2})\b/i)||text.match(/^0?(\d{1,2})\s*[•·—:\-]/);if(m&&chamber(pad(m[1])))return pad(m[1]);const low=text.toLowerCase();for(const [name,id] of nameIndex)if(name&&low.includes(name))return id;return '';}
  function inferFromNode(node){let el=node?.nodeType===1?node:node?.parentElement;for(let depth=0;el&&depth<6;depth++,el=el.parentElement){const id=inferFromText(el.getAttribute?.('aria-label')||'')||inferFromText(el.textContent||'');if(id)return id;}return '';}
  function findChamberElement(id){const p=chamber(id);if(!p)return null;const needles=[`CHAMBER ${Number(id)}`,`CHAMBER ${id}`,p.thirdName].map(s=>s.toLowerCase());const matches=$$('article,section,[role="dialog"],button,div').filter(el=>{const t=(el.textContent||'').toLowerCase();return needles.some(n=>t.includes(n))&&el.getBoundingClientRect().height>0;});return matches.sort((a,b)=>(a.textContent||'').length-(b.textContent||'').length)[0]||null;}
  function goTo(id){id=pad(id);const el=findChamberElement(id);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});if(el.matches('button,[role="button"]'))el.click();else el.querySelector('button,[role="button"]')?.click();setCurrent(id);}else{setCurrent(id);location.hash=`chamber-${id}`;}closeEntrance();}
  function randomChamber(){goTo(pad(1+Math.floor(Math.random()*72)));}
  function ritualButton(){const buttons=$$('button').filter(b=>b.offsetParent!==null&&!b.disabled);return buttons.find(b=>/RITUAL/i.test(b.textContent||''))||buttons.find(b=>/^(PLAY|PAUSE|RESUME)(\s+(MUSIC|SOUND|AUDIO))?$/i.test((b.textContent||'').trim()))||null;}
  function triggerRitual(){const b=ritualButton();if(b)b.click();else alert('Open the Temple ritual/audio control first, then use Ritual again.');setTimeout(refreshDock,120);}
  function ritualText(){const t=(ritualButton()?.textContent||'').trim();return /PAUSE/i.test(t)?'Pause Ritual':/RESUME/i.test(t)?'Resume Ritual':'Play Ritual';}
  function replaceLegacySeals(root=document){$$('img',root).forEach(img=>{const alt=(img.alt||'').toLowerCase();if(!alt.includes('seal'))return;const id=inferFromNode(img);if(!id||img.dataset.tm621Seal===id)return;const p=chamber(id);img.src=svgDataUri(sealSvg(p,640));img.dataset.tm621Seal=id;img.alt=`Human-origin seal of ${p.thirdName}`;});}
  function interceptSealDownloads(e){const b=e.target.closest('button,a');if(!b)return;const txt=(b.textContent||b.getAttribute('aria-label')||'').trim();if(!/seal/i.test(txt)||!/download|png|save/i.test(txt)||/72|all/i.test(txt))return;const id=inferFromNode(b)||currentId;if(!id)return;e.preventDefault();e.stopImmediatePropagation();downloadSealPng(chamber(id),b);}
  function ensureShell(){if($('#tm621-shell'))return;const shell=document.createElement('div');shell.id='tm621-shell';shell.innerHTML=`
    <button id="tm621-enter" type="button" aria-haspopup="dialog">Temple Entrance</button>
    <button id="tm621-version" type="button" aria-haspopup="dialog">Temple v${VERSION}</button>
    <aside id="tm621-dock" aria-live="polite"><div class="tm621-dock-meta"><span>CHAMBER</span><strong>—</strong></div><div class="tm621-dock-actions"><button data-dock="ritual">Play Ritual</button><button data-dock="collect">Collect</button><button data-dock="seal">Seal</button><button data-dock="method">Method</button></div></aside>
    <div id="tm621-entrance" class="tm621-backdrop" hidden><section class="tm621-modal tm621-entrance" role="dialog" aria-modal="true" aria-labelledby="tm621-entry-title"><button class="tm621-close" data-close="entrance" aria-label="Close Temple Entrance">✕</button><div class="tm621-kicker">TEMPLE OF MA’AT • REFINED ENTRANCE</div><h2 id="tm621-entry-title">Enter with intention.</h2><p class="tm621-lead">The primary path is Chamber → Office → Law → Ritual → deliberate Collection. Utilities remain available without competing with the chamber itself.</p><div class="tm621-progress"><strong data-progress>Visited 0 • Collected 0 / 72</strong><div><i data-visited-bar></i><b data-collected-bar></b></div></div><div class="tm621-entry-grid"><button class="primary" data-entry="enter"><strong>Enter Temple</strong><span>Return to the living chamber archive.</span></button><button data-entry="continue"><strong>Continue</strong><span>Return to the last chamber you visited.</span></button><button data-entry="seals"><strong>Human-Origin Seal Library</strong><span>72 semantic seals: seven Fires, three Pillars, one human center.</span></button><button data-entry="parental"><strong>Parental Powers</strong><span>Preserved 72-wallpaper rail and archive.</span></button><button data-entry="method"><strong>About & Methodology</strong><span>Historical reference, manuscript tradition, and Temple synthesis.</span></button></div><details class="tm621-utilities"><summary>Utilities & Downloads</summary><div><button data-entry="random">Random Chamber</button><a href="${WALLPAPER_ZIP}" download>Download 72 Wallpapers</a><button data-entry="status">App Status</button></div></details><footer>Temple v${VERSION} • ${BUILD}<br>Site Administrator: Alberto Ramirez • © 2026 Alberto Ramirez</footer></section></div>
    <div id="tm621-method" class="tm621-backdrop" hidden><section class="tm621-modal tm621-method" role="dialog" aria-modal="true" aria-labelledby="tm621-method-title"><button class="tm621-close" data-close="method">✕</button><div class="tm621-kicker">ABOUT • METHODOLOGY • PROVENANCE</div><h2 id="tm621-method-title">Discern the source layer.</h2><div class="tm621-source-grid"><article><span>HISTORICAL EGYPTIAN REFERENCE</span><h3>Ma’at</h3><p>The Temple uses Ma’at as an ethical-cosmological reference—truth, right order, justice, balance, the feather, and heart-weighing imagery—while distinguishing that history from the project’s modern chamber system.</p></article><article><span>MANUSCRIPT / OCCULT-HISTORY REFERENCE</span><h3>Solomonic traditions</h3><p>Later manuscript traditions attributed to Solomon inform names and visual language. They are not evidence that this Temple’s 72-chamber construction existed in ancient Egypt or during the historical reign of Solomon.</p></article><article class="synthesis"><span>ORIGINAL TEMPLE SYNTHESIS</span><h3>The 72 chambers</h3><p>Angel ↔ daemon pairings, reconciled third names, seven Fires, Offices, Laws, and the human-origin seal grammar are creative interpretive constructions of this project.</p></article><article><span>INTERPRETIVE USE</span><h3>Discernment before authority</h3><p>The archive is for symbolic reflection, comparative study, art, and personal discernment. It does not replace historical scholarship, psychological or medical care, or religious authority.</p></article></div><div class="tm621-links"><a href="./methodology.html">Open full methodology page</a><a href="./seal-system.json">Inspect seal grammar data</a></div></section></div>
    <div id="tm621-seals" class="tm621-backdrop" hidden><section class="tm621-modal tm621-seal-modal" role="dialog" aria-modal="true" aria-labelledby="tm621-seal-title"><header><div><div class="tm621-kicker">72 HUMAN-ORIGIN SEALS</div><h2 id="tm621-seal-title">One human center. Meaningful variation.</h2></div><button class="tm621-close" data-close="seals">✕</button></header><div class="tm621-seal-tools"><input type="search" placeholder="Search chamber, Fire, Pillar…" aria-label="Search seals"><span data-seal-count>72 seals</span></div><div class="tm621-seal-grid"></div></section></div>
    <div id="tm621-status" class="tm621-backdrop" hidden><section class="tm621-modal tm621-status" role="dialog" aria-modal="true"><button class="tm621-close" data-close="status">✕</button><div class="tm621-kicker">TEMPLE DIAGNOSTICS</div><h2>Temple v${VERSION}</h2><dl><dt>Build</dt><dd>${BUILD}</dd><dt>Connection</dt><dd data-online>${navigator.onLine?'Online':'Offline'}</dd><dt>Service Worker</dt><dd data-sw>Checking…</dd><dt>Visited</dt><dd data-vcount>0</dd><dt>Collected</dt><dd data-ccount>0</dd><dt>Parental Powers</dt><dd>${powers.length||72} preserved</dd></dl><button data-entry="reload">Reload Updated Temple</button></section></div>`;
    document.body.appendChild(shell);wireShell();refreshDock();refreshProgress();}
  function modal(id,open=true){const el=$(id);if(!el)return;el.hidden=!open;document.documentElement.classList.toggle('tm621-modal-open',open||$$('.tm621-backdrop').some(x=>!x.hidden));if(open)setTimeout(()=>$('.tm621-close',el)?.focus(),20);}
  function openEntrance(){modal('#tm621-entrance',true);session().setItem(SESSION_KEY,'1');refreshProgress();}
  function closeEntrance(){modal('#tm621-entrance',false);}
  function openMethod(){modal('#tm621-method',true);}
  function openSeals(){renderSealLibrary();modal('#tm621-seals',true);}
  function openStatus(){refreshStatus();modal('#tm621-status',true);}
  function parental(){const candidates=$$('button,a,[role="button"],h2,h3').filter(x=>/parental powers|wallpaper/i.test(x.textContent||''));const target=candidates.find(x=>x.offsetParent!==null);if(target){target.scrollIntoView({behavior:'smooth',block:'center'});if(target.matches('button,a,[role="button"]'))target.click();}else window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});closeEntrance();}
  function wireShell(){
    $('#tm621-enter').onclick=openEntrance;$('#tm621-version').onclick=openStatus;
    $('#tm621-dock').addEventListener('click',e=>{const a=e.target.closest('[data-dock]')?.dataset.dock;if(a==='ritual')triggerRitual();if(a==='collect'&&currentId)collect(currentId);if(a==='seal'){if(currentId){openSeals();setTimeout(()=>document.querySelector(`[data-seal-id="${currentId}"]`)?.scrollIntoView({block:'center'}),80);}else openSeals();}if(a==='method')openMethod();});
    $('#tm621-shell').addEventListener('click',e=>{const c=e.target.closest('[data-close]')?.dataset.close;if(c)modal(`#tm621-${c}`,false);const a=e.target.closest('[data-entry]')?.dataset.entry;if(!a)return;if(a==='enter')closeEntrance();if(a==='continue'){const id=storage().getItem(LAST_KEY)||[...readSet(VISITED_KEY)].sort().pop()||'01';goTo(id);}if(a==='seals')openSeals();if(a==='parental')parental();if(a==='method')openMethod();if(a==='random')randomChamber();if(a==='status')openStatus();if(a==='reload')location.reload();});
    $$('.tm621-backdrop').forEach(back=>back.addEventListener('click',e=>{if(e.target===back)modal('#'+back.id,false);}));
    $('#tm621-seals input').addEventListener('input',renderSealLibrary);
  }
  function refreshDock(){const dock=$('#tm621-dock');if(!dock)return;const p=chamber(currentId);$('.tm621-dock-meta strong',dock).textContent=p?`${p.id} • ${p.thirdName}`:'Choose a chamber';const rb=$('[data-dock="ritual"]',dock);rb.textContent=ritualText();const cb=$('[data-dock="collect"]',dock);const collected=p&&readSet(COLLECTED_KEY).has(p.id);cb.textContent=collected?'Collected ✓':'Collect';cb.disabled=!p||collected;}
  function refreshProgress(){const v=readSet(VISITED_KEY).size,c=readSet(COLLECTED_KEY).size;$$('[data-progress]').forEach(x=>x.textContent=`Visited ${v} • Collected ${c} / 72`);$$('[data-visited-bar]').forEach(x=>x.style.width=`${v/72*100}%`);$$('[data-collected-bar]').forEach(x=>x.style.width=`${c/72*100}%`);$$('[data-vcount]').forEach(x=>x.textContent=v);$$('[data-ccount]').forEach(x=>x.textContent=c);}
  function refreshStatus(){refreshProgress();const sw=$('[data-sw]');if(sw){if(!('serviceWorker' in navigator))sw.textContent='Not supported';else navigator.serviceWorker.getRegistration().then(r=>sw.textContent=r?`${r.active?'Active':'Registered'} • ${r.scope}`:'Not registered').catch(()=>sw.textContent='Unavailable');}$('[data-online]')?.replaceChildren(document.createTextNode(navigator.onLine?'Online':'Offline'));}
  function renderSealLibrary(){const grid=$('.tm621-seal-grid');if(!grid)return;const q=($('#tm621-seals input')?.value||'').toLowerCase().trim();const items=powers.filter(p=>!q||[p.id,p.thirdName,p.angel,p.daemon,p.office,p.law,p.pillar,p.fire?.name].some(v=>String(v||'').toLowerCase().includes(q)));grid.innerHTML=items.map(p=>`<article class="tm621-seal-card" data-seal-id="${p.id}"><div class="tm621-seal-art">${sealSvg(p,360)}</div><div class="tm621-seal-meta"><strong>${p.id} • ${esc(p.thirdName)}</strong><span>${esc(p.angel)} ↔ ${esc(p.daemon)}</span><small>${esc(p.pillar)} • ${esc(p.fire?.name)}</small></div><div class="tm621-seal-actions"><button data-seal-view="${p.id}">Open Chamber</button><button data-seal-download="${p.id}">PNG</button><button data-seal-collect="${p.id}" ${readSet(COLLECTED_KEY).has(p.id)?'disabled':''}>${readSet(COLLECTED_KEY).has(p.id)?'Collected ✓':'Collect'}</button></div></article>`).join('');$('[data-seal-count]').textContent=`${items.length} seal${items.length===1?'':'s'}`;grid.querySelectorAll('[data-seal-view]').forEach(b=>b.onclick=()=>{modal('#tm621-seals',false);goTo(b.dataset.sealView);});grid.querySelectorAll('[data-seal-download]').forEach(b=>b.onclick=()=>downloadSealPng(chamber(b.dataset.sealDownload),b));grid.querySelectorAll('[data-seal-collect]').forEach(b=>b.onclick=()=>{collect(b.dataset.sealCollect);renderSealLibrary();});}
  function renderSealLibraryCounts(){if(!$('#tm621-seals')?.hidden)renderSealLibrary();}
  function observeTemple(){document.addEventListener('click',e=>{interceptSealDownloads(e);const id=inferFromNode(e.target);if(id)setCurrent(id);if(e.target.closest('button'))setTimeout(refreshDock,100);},true);window.addEventListener('hashchange',()=>{const m=location.hash.match(/chamber[-_]?0?(\d{1,2})/i);if(m)setCurrent(m[1]);});window.addEventListener('online',refreshStatus);window.addEventListener('offline',refreshStatus);document.addEventListener('temple:collection-change',refreshProgress);const obs=new MutationObserver(muts=>{for(const m of muts)for(const n of m.addedNodes)if(n.nodeType===1)replaceLegacySeals(n);refreshDock();});obs.observe(document.body,{childList:true,subtree:true});replaceLegacySeals();}
  function initData(){const raw=window.TEMPLE_PARENTAL_POWERS;if(!raw)return false;powers=(Array.isArray(raw)?raw:Object.values(raw)).filter(p=>p&&p.id).sort((a,b)=>Number(a.id)-Number(b.id)).map(p=>({...p,id:pad(p.id)}));if(powers.length<72)return false;nameIndex=powers.map(p=>[String(p.thirdName||'').toLowerCase(),p.id]).filter(x=>x[0]).sort((a,b)=>b[0].length-a[0].length);return true;}
  function boot(attempt=0){if(!initData()){if(attempt<80)return setTimeout(()=>boot(attempt+1),100);console.warn('Temple refinement: parental/chamber metadata unavailable');return;}ensureShell();observeTemple();const m=location.hash.match(/chamber[-_]?0?(\d{1,2})/i);if(m)setCurrent(m[1]);else{const last=storage().getItem(LAST_KEY);if(last&&chamber(last))currentId=last;refreshDock();}window.TempleRefinement=Object.freeze({version:VERSION,build:BUILD,openEntrance,openMethodology:openMethod,openSealLibrary:openSeals,sealSvg,visited:()=>[...readSet(VISITED_KEY)],collected:()=>[...readSet(COLLECTED_KEY)],collect,setCurrent});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>boot());else boot();
})();
